### ISSUE TITLE
NPE while dialogs are being created

### ISSUE THREAD

**Issue by Nevel** [PavlikPolivka/GitLabProjects#103]
This plugin has always worked fine for me, up until version 2018.2.

Both the "Git -> Git Lab -> Create Merge Request" and "Git -> Git Lab -> List Merge Requests" actions now trigger a NPE. The short version of the stacktrace is as follows:

java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at com.ppolivka.gitlabprojects.merge.list.CodeReviewDialog.$$$setupUI$$$(CodeReviewDialog.java)
	at com.ppolivka.gitlabprojects.merge.list.CodeReviewDialog.<init>(CodeReviewDialog.java:48)
	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListDialog.doOKAction(GitLabMergeRequestListDialog.java:63)

After browsing your code for a bit, I suspect the issue occurs while attempting to render images for _diffButton_ and _commentsButton_.

Please let me know if I should add any more info.

**Comment by PavlikPolivka** [comment]
Hi.
2018.2 is EAP?

**Comment by PavlikPolivka** [comment]
I release 182.2 version of the plugin with fixed icons, not sure if EAP will get this new version from ide update.
