### ISSUE TITLE
Trying to make an initial share not reciving any message 

### ISSUE THREAD

**Issue by anthonyjrg** [PavlikPolivka/GitLabProjects#105]
This is the error log
null
java.lang.NullPointerException
	at com.ppolivka.gitlabprojects.util.GitLabUtil.findGitLabRemote(GitLabUtil.java:82)
	at com.ppolivka.gitlabprojects.util.GitLabUtil.findGitLabRemoteUrl(GitLabUtil.java:71)
	at com.ppolivka.gitlabprojects.share.GitLabShareAction.shareProjectOnGitLab(GitLabShareAction.java:75)
	at com.ppolivka.gitlabprojects.share.GitLabShareAction.apiValidAction(GitLabShareAction.java:63)
	at com.ppolivka.gitlabprojects.common.NoGitLabApiAction.actionPerformed(NoGitLabApiAction.java:50)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.a(ActionMenuItem.java:301)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:307)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:104)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:291)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.a(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:528)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:48)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:548)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.m(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:716)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by PavlikPolivka** [comment]
Hi.

Plugin is trying to find a gitlab project in the list of your remores.
If yiu do git remote -v you should see list of all remotes, is there a remote with same url you have in the settings in the plugin settings (File, Settings, Gitlab Projects).

It does not have to be the same url, but the hostname etc must be same. 
If you can provide me with the list of remotes and how the plugin is setup I can help you troubleshoot, if you do not want to get this list into to a public forum you can email to me at polivka.pavel@gmail.com 

Pavel

**Comment by imekachi** [comment]
@PavlikPolivka I'm still getting the error. I've sent emails to you with screenshots and error logs.

**Comment by ResleyR** [comment]
I too get the same error. My gitlab installation is hosted on a non standard port so the url usually includes the port (http://example.com:1234/) or for my git to work with ssh I have a config with an alias that points to the correct hostname:port combination.

Could this be a reason for it? I've used the same url & token with another plugin and that plugin works

**Comment by PavlikPolivka** [comment]
Hi all.
I am in the middle of moving so I do not have time to fix this right now.

How the plugin works is that it takes the url of your gitlab installation you provided with credentials and when working with git repo it goes over all the remotes and tries to find that gitlab between remotes.

This usually works, except in edge cases when somebody is running non standard installations of gitlab..

So the non standard port can mess this up. 
Also when you input your gitlab url with http and checkout repo with https url it tends to fail as well. 

What I am planning to do is to provide "advanced" setting for each gitlab setting in the plugin that would be the second url that can be used for remote identification. This would solve most of these issues. 

Unfortunately I do not have time to implement this right now earliest possible date is end of September.

**Comment by PavlikPolivka** [comment]
Hi. I just reelased new version of the plugin with new settings diallog. In there you can specify URL to the UI part of your gitlab and repo part.

This should solve most of theese issues. 
I also added documentation here https://github.com/PavlikPolivka/GitLabProjects/wiki/Gitlab-Projects-Jetbrains-IDE-plugin 

Please reopen if this did not solve your issues.

**Comment by ResleyR** [comment]
This is the log I get when I try it now.
> java.lang.NullPointerException
> 	at com.ppolivka.gitlabprojects.util.GitLabUtil.findGitLabRemote(GitLabUtil.java:82)
> 	at com.ppolivka.gitlabprojects.merge.GitLabMergeRequestWorker$Util.fillRequiredInfo(GitLabMergeRequestWorker.java:87)
> 	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListWorker$2.convert(GitLabMergeRequestListWorker.java:74)
> 	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListWorker$2.convert(GitLabMergeRequestListWorker.java:68)
> 	at com.ppolivka.gitlabprojects.util.GitLabUtil$2.run(GitLabUtil.java:207)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:434)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:574)
> 	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
