### ISSUE TITLE
Failed to connect via API V3

### ISSUE THREAD

**Issue by vsevolod-rijov** [PavlikPolivka/GitLabProjects#109]
Hi.
I'm using PhpStorm 2017.2.5 and GitLab Project 1.5.3
There is an error on updating gitlab project list:

`java.io.FileNotFoundException:
 https://gitlab.com/api/v3/namespaces?private_token=<MY TOKEN>
java.lang.Error: java.io.FileNotFoundException: https://gitlab.com/api/v3/namespaces?private_token=<MY TOKEN>
	at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:239)
	at org.gitlab.api.http.GitlabHTTPRequestor$1.hasNext(GitlabHTTPRequestor.java:193)
	at org.gitlab.api.http.GitlabHTTPRequestor.getAll(GitlabHTTPRequestor.java:161)
	at com.ppolivka.gitlabprojects.api.ApiFacade.getNamespaces(ApiFacade.java:51)
	at com.ppolivka.gitlabprojects.share.GitLabShareDialog$3.run(GitLabShareDialog.java:124)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: https://gitlab.com/api/v3/namespaces?private_token=<MY TOKEN>
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:324)
	at org.gitlab.api.http.GitlabHTTPRequestor.access$200(GitlabHTTPRequestor.java:28)
	at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:232)
	... 17 more`

I have this error "API V3 is no longer supported. Use API V4 instead." on curl to https://gitlab.com/api/v3/namespaces?private_token=MY TOKEN

**Comment by PavlikPolivka** [comment]
Update the plugin. This is fixed in 1.7.0 you may need to update the ide as
well because plugin no longer supports 2017 versions. Sorry I am not able
to do this kind of fixes for all the legacy ide versions...

Pavel

**Comment by vsevolod-rijov** [comment]
Hi.

Thx for reply. I have updated PhpStorm to 2018.1.6 and GitLab Projects to 1.7.0 versions.
Now there is no GitLab menu item in "Check out from Version Control" dropdown list on Welcome to PhpStorm window.

**Comment by PavlikPolivka** [comment]
It's IDE change. There is now one git checkou dialog that is supporting
multiple git providers. If you do normal git checkout your gitlab projects
will be autocompleted for you.

**Comment by vsevolod-rijov** [comment]
Thanks, it work's now
