### ISSUE TITLE
IllegalStateException in "Create Merge Request" dialog

### ISSUE THREAD

**Issue by buffcode** [PavlikPolivka/GitLabProjects#13]
Reproduce:
VCS -> Gitlab -> Create merge request
Active window: Editor
1 commit ahead of master

```
The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[ApplicationImpl pooled thread 17,4,main]
java.lang.IllegalStateException: The DialogWrapper can only be used in event dispatch thread. Current thread: Thread[ApplicationImpl pooled thread 17,4,main]
	at com.intellij.openapi.ui.DialogWrapper.ensureEventDispatchThread(DialogWrapper.java:2016)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1184)
	at com.intellij.openapi.ui.Messages$MessageDialog._init(Messages.java:1383)
	at com.intellij.openapi.ui.Messages$MessageDialog.<init>(Messages.java:1308)
	at com.intellij.openapi.ui.Messages.showIdeaMessageDialog(Messages.java:174)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:161)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:130)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:683)
	at com.ppolivka.gitlabprojects.merge.GitLabMergeRequestWorker$8.convert(GitLabMergeRequestWorker.java:368)
	at com.ppolivka.gitlabprojects.merge.GitLabMergeRequestWorker$8.convert(GitLabMergeRequestWorker.java:311)
	at com.ppolivka.gitlabprojects.common.GitLabUtils$2.run(GitLabUtils.java:187)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$14$1.run(ApplicationImpl.java:626)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by PavlikPolivka** [comment]
Yes, sorry this was working on my project that was imported to GitLab via this plugin. I did not check if this merge requested thing works on other projects also.

I am fixing this now, fix should be released soon.

**Comment by PavlikPolivka** [comment]
Fix submited to JetBrains plugin repo. Closing this issue
