### ISSUE TITLE
Limit the scope needed for tokens

### ISSUE THREAD

**Issue by dms-cat** [PavlikPolivka/GitLabProjects#137]
I just configured this plugin with a token which has only "read_user" and "read_repository" access, and it accepted the token but doesn't seem to work. For example:

1. Configure the server (I thought the repository URL was supposed to be the URL of the repository, but it isn't).
1. Open the context menu and click "Git" → "Git Lab" (sic) → "List Merge Requests" → Optionally select a server → "OK".
1. When trying to list merge requests using the context menu I first get the server list, and get the following stacktrace:

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'mergeRequestListWorker' of com/ppolivka/gitlabprojects/merge/list/GitLabMergeRequestListDialog.<init> must not be null
	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListDialog.$$$reportNull$$$0(GitLabMergeRequestListDialog.java)
	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListDialog.<init>(GitLabMergeRequestListDialog.java)
	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListAction.apiValidAction(GitLabMergeRequestListAction.java:23)
	at com.ppolivka.gitlabprojects.common.GitLabApiAction.actionPerformed(GitLabApiAction.java:58)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:287)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:106)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:277)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:522)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:35)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:544)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

This leads to some questions:

- Does this plugin *require* the "api" scope?
- Could the required scope be mentioned near the "GitLab Personal Access Token" field, perhaps as hover text?
- Could read only operations such as listing merge requests fall back gracefully to using the "read_repository" scope? I realize this might be quite a bit of work, since it's a completely redundant access method.

**Comment by PavlikPolivka** [comment]
Hi. This plugin was develop before scopes in Gitlab existed as 95% of the operations are using some api actions my guess is that it requires the api scope. 

My guess is that you are confused about what each scope does .. - read_repository scope allows to read the actual git repository, merge requests are not part of git repository .. those are gitlab construct over the repository and to list them you need to list them by their API (there is no git command to list gitlab merge requests) .. to read from API (even if it's read only) you need to have api scope ... unfortunately there is no read only api scope in gitlab 

You only option is to have the api scope on the token to use most of this plugin (I will add this to the dialog when I will have a minute).
