### ISSUE TITLE
PHPStorm quick search triggers exception

### ISSUE THREAD

**Issue by buffcode** [PavlikPolivka/GitLabProjects#14]
When doing a quick search (double shift), an exception is triggered:

```
Access is allowed from event dispatch thread only.
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@d0e53d Current thread: Thread[ApplicationImpl pooled thread 38,4,main] 28374968 SystemEventQueueThread: Thread[AWT-EventQueue-0 10.0.1#PS-143.382.38, eap:false,6,main] 11793631

java.lang.Throwable
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:497)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:29)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:1106)
	at com.intellij.openapi.application.impl.ApplicationImpl.f(ApplicationImpl.java:1090)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1082)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.p(FocusManagerImpl.java:1200)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.isFocusTransferReady(FocusManagerImpl.java:680)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.isFocusBeingTransferred(FocusManagerImpl.java:1153)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.isFocusBeingTransferred(IdeFocusManagerImpl.java:144)
	at com.intellij.ide.impl.DataManagerImpl.a(DataManagerImpl.java:248)
	at com.intellij.ide.impl.DataManagerImpl.getDataContext(DataManagerImpl.java:202)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.<init>(DialogWrapperPeerImpl.java:100)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerFactoryImpl.createPeer(DialogWrapperPeerFactoryImpl.java:37)
	at com.intellij.openapi.ui.DialogWrapper.createPeer(DialogWrapper.java:796)
	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:215)
	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:211)
	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:245)
	at com.ppolivka.gitlabprojects.configuration.ConfigurationDialog.<init>(ConfigurationDialog.java:49)
	at com.ppolivka.gitlabprojects.configuration.SettingsConfigurableProvider.createConfigurable(SettingsConfigurableProvider.java:18)
	at com.intellij.openapi.options.ConfigurableEP$ProviderProducer.createElement(ConfigurableEP.java:326)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:273)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.a(ConfigurableWrapper.java:54)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.wrapConfigurable(ConfigurableWrapper.java:49)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.a(ConfigurableExtensionPointUtil.java:333)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurableGroup(ConfigurableExtensionPointUtil.java:142)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurableGroups(ShowSettingsUtilImpl.java:79)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurables(ShowSettingsUtilImpl.java:94)
	at com.intellij.ide.actions.SearchEverywhereAction$CalcThread.b(SearchEverywhereAction.java:2040)
	at com.intellij.ide.actions.SearchEverywhereAction$CalcThread.run(SearchEverywhereAction.java:1378)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```
[threadDump.txt](https://github.com/PavlikPolivka/GitLabProjects/files/36492/threadDump.txt)

**Comment by PavlikPolivka** [comment]
Should be fixed, version 1.2.2 submitted to JetBrains plugin repository.
