### ISSUE TITLE
Plugin crashes in Pycharm 2019.1

### ISSUE THREAD

**Issue by EricVS** [PavlikPolivka/GitLabProjects#144]
Just installed the plugin, added my GitLab server but when I try to either create a merge request or list the merge request, it crashes with the below stacktrace.

```bash
java.lang.NullPointerException
	at com.ppolivka.gitlabprojects.util.GitLabUtil.findGitLabRemote(GitLabUtil.java:82)
	at com.ppolivka.gitlabprojects.merge.GitLabMergeRequestWorker$Util.fillRequiredInfo(GitLabMergeRequestWorker.java:87)
	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListWorker$2.convert(GitLabMergeRequestListWorker.java:74)
	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListWorker$2.convert(GitLabMergeRequestListWorker.java:68)
	at com.ppolivka.gitlabprojects.util.GitLabUtil$2.run(GitLabUtil.java:207)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:594)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by imchipwood** [comment]
I'm seeing the same error in 2018.2.
