### ISSUE TITLE
Plugin does not work in IDEA 2019.1 Linux

### ISSUE THREAD

**Issue by gfstein** [PavlikPolivka/GitLabProjects#154]
Staktrace after I try submmit a merge request:

`java.lang.NullPointerException
	at com.ppolivka.gitlabprojects.util.GitLabUtil.findGitLabRemote(GitLabUtil.java:82)
	at com.ppolivka.gitlabprojects.merge.GitLabMergeRequestWorker$Util.fillRequiredInfo(GitLabMergeRequestWorker.java:87)
	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListWorker$2.convert(GitLabMergeRequestListWorker.java:74)
	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListWorker$2.convert(GitLabMergeRequestListWorker.java:68)
	at com.ppolivka.gitlabprojects.util.GitLabUtil$2.run(GitLabUtil.java:207)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:594)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by durino13** [comment]
I have the same problem.

**Comment by partikule** [comment]
Exactly the same problem.

**Comment by geekMessi** [comment]
+1
