### ISSUE TITLE
WS 2020.1 incompatibility

### ISSUE THREAD

**Issue by vegerot** [PavlikPolivka/GitLabProjects#176]
```
12:29 PM	Plugin Error: Plugin ".ignore" is incompatible (until build 201.0 < WS-201.6668.106).
```

```
com.intellij.diagnostic.PluginException: java.lang.reflect.InvocationTargetException [Plugin: com.ppolivka.gitlabprojects]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:201)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:171)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:527)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:515)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1504)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:15)
	at com.intellij.openapi.application.Preloader.lambda$null$1(Preloader.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.Preloader.lambda$null$2(Preloader.java:75)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:116)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:449)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:190)
	... 20 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:430)
	... 21 more
Caused by: java.lang.NoSuchFieldError: MergeSourcesTree
	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListAction.<init>(GitLabMergeRequestListAction.java:17)
	... 26 more
```

**Comment by webcoderkz** [comment]
Same bug, would love to use it on 2020.1
@PavlikPolivka do you plan it to update?

**Comment by webcoderkz** [comment]
This project is dead probably, removing it. All i used from it - was creating a merge requests from IDE (was convenient), but i can do that from gitlab interface anyway.

**Comment by vegerot** [comment]
@webcoderkz I found it very valuable.  Not for creating merge requests, but the ability to review, assign, and merge them form WebStorm.  It has really been hurting my workflow over the last few days

**Comment by webcoderkz** [comment]
tbh, JB must make their own gitlab integration, just like github's.

**Comment by vegerot** [comment]
Do they?  I think they support [issues and tasks](https://www.jetbrains.com/help/webstorm/managing-tasks-and-context.html), but not merge requests.  Oh yeah, the other thing I use this plugins TONS for is "open in GitLab" and "copy link to GitLab".

**Comment by webcoderkz** [comment]
I have mistaken, they do not have a Pull request feature for github.

**Comment by burzillibus** [comment]
I notice the same problem in PC 2020.1 and in IJ (same version).
The plugin is working properly, so I think it could be only a false negative, but it's annoing to see the error in the IDE, mine are enough :)

**Comment by vegerot** [comment]
@burzillibus I can't seem to be able to view open merge requests.  Can you?

**Comment by burzillibus** [comment]
I'm sorry @vegerot, I'm referring to the main the incompatibility of the plugin with PyCharm and IntelliJ 2020.1. I haven't open any merge request.

**Comment by vegerot** [comment]
alright, thanks

**Comment by xionghaizhi** [comment]
Is there a solution? Or alternatives?

**Comment by vegerot** [comment]
Just use gitlab.com lol

But seriously, WebStorm comes with the ability to do some of these things with its builtin GitLab integration, but it cannot do everything this plugin can.  For that, either use GitLab.com or learn JetBrains' API and make your own, better plugin!

**Comment by ptv1p3r** [comment]
Is this dead or will any update come soon? getting :
com.intellij.diagnostic.PluginException: java.lang.reflect.InvocationTargetException [Plugin: com.ppolivka.gitlabprojects]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:200)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:170)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:526)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:514)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1510)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:15)
	at com.intellij.openapi.application.Preloader.lambda$null$1(Preloader.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.application.Preloader.lambda$null$2(Preloader.java:75)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:116)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:449)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:189)
	... 20 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:430)
	... 21 more
Caused by: java.lang.NoSuchFieldError: MergeSourcesTree
	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListAction.<init>(GitLabMergeRequestListAction.java:17)
	... 26 more

**Comment by vegerot** [comment]
😫
