### ISSUE TITLE
NullPointerException when creating merge request

### ISSUE THREAD

**Issue by finsterwalder** [PavlikPolivka/GitLabProjects#177]
java.lang.NullPointerException
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at com.ppolivka.gitlabprojects.merge.request.CreateMergeRequestDialog.$$$setupUI$$$(CreateMergeRequestDialog.java)
	at com.ppolivka.gitlabprojects.merge.request.CreateMergeRequestDialog.<init>(CreateMergeRequestDialog.java:49)
	at com.ppolivka.gitlabprojects.merge.request.GitLabMergeRequestAction.apiValidAction(GitLabMergeRequestAction.java:30)
	at com.ppolivka.gitlabprojects.common.GitLabApiAction.actionPerformed(GitLabApiAction.java:58)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:609)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:669)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:619)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:516)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:470)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:219)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:896)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by seliver** [comment]
This is happening to me as well.
Basically happens when one clicks/selects the option to create a merge request. 

It is expected for a window to open up, but instead this error appears in the lower right end corner under "IDE Internal Error Occured".

This is definitely happening because of the update, otherwise it worked fine.

More info:
PHPStorm version 2020.1
Build: PS-201.6668.153
Runtime version: 11.0.6+8-b765.25 x86_64

**Comment by wudeyong** [comment]
I fork this project and fix it, u gays can download from here:
https://plugins.jetbrains.com/plugin/14110-gitlab-projects-2020

**Comment by MathieuLavigneCC** [comment]
Thanks @wudeyong for your work. Unfortunatly I cannot make it work with IntelliJ due to conflicts with the original plugin.

If I activate both plugins I cannot start IntelliJ.
If I activate only yours, neither VCS > Git > GitLab nor GitLab settings are available.

Does anybody experience the same problem ?

**Comment by wudeyong** [comment]
> Thanks @wudeyong for your work. Unfortunatly I cannot make it work with IntelliJ due to conflicts with the original plugin.
> 
> If I activate both plugins I cannot start IntelliJ.
> If I activate only yours, neither VCS > Git > GitLab nor GitLab settings are available.
> 
> Does anybody experience the same problem ?

You can uninstall the old plugin fully, and install the gitlab-projects-2020, It works on my ide

**Comment by MathieuLavigneCC** [comment]
Thanks for your support, it worked like a charm. I was disabling the old plugin instead of uninstalling.
