### ISSUE TITLE
IllegalMonitorStateException: null

### ISSUE THREAD

**Issue by orf** [PavlikPolivka/GitLabProjects#28]
Hi,
This plugin looks awesome, thanks for your work. I was trying it out and attempting to make a merge request from my branch. After I select create a merge request (or list merge requests) the following error is triggered:

```
null
java.lang.IllegalMonitorStateException
	at java.lang.Object.notify(Native Method)
	at com.ppolivka.gitlabprojects.merge.GitLabMergeRequestWorker$Util.fillRequiredInfo(GitLabMergeRequestWorker.java:110)
	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListWorker$2.convert(GitLabMergeRequestListWorker.java:74)
	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListWorker$2.convert(GitLabMergeRequestListWorker.java:68)
	at com.ppolivka.gitlabprojects.util.GitLabUtil$2.run(GitLabUtil.java:194)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$13$1.run(ApplicationImpl.java:633)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This appears to happen if your gitlab server runs over `https` but you specify a `http` prefix in your URL.

**Comment by PavlikPolivka** [comment]
I removed unused line, that was probably causing this issue. If user has wrong settings it should display error message, no null pointer.
