### ISSUE TITLE
java.io.IOException on "List Merge Requests"

### ISSUE THREAD

**Issue by ToScope** [PavlikPolivka/GitLabProjects#38]
When opening the "List Merge Requests" the following exception occurs:

`java.io.IOException: {"message":"500 Internal Server Error"}
java.lang.Error: java.io.IOException: {"message":"500 Internal Server Error"}
    at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:220)
    at org.gitlab.api.http.GitlabHTTPRequestor$1.hasNext(GitlabHTTPRequestor.java:176)
    at org.gitlab.api.http.GitlabHTTPRequestor.getAll(GitlabHTTPRequestor.java:145)
    at org.gitlab.api.GitlabAPI.getAllMergeRequests(GitlabAPI.java:320)
    at org.gitlab.api.GitlabAPI.getOpenMergeRequests(GitlabAPI.java:295)
    at com.ppolivka.gitlabprojects.api.ApiFacade.getMergeRequests(ApiFacade.java:52)
    at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListWorker$2.convert(GitLabMergeRequestListWorker.java:80)
    at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListWorker$2.convert(GitLabMergeRequestListWorker.java:68)
    at com.ppolivka.gitlabprojects.util.GitLabUtil$2.run(GitLabUtil.java:206)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
    at com.intellij.openapi.progress.impl.CoreProgressManager$9.run(CoreProgressManager.java:384)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:556)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: {"message":"500 Internal Server Error"}
    at org.gitlab.api.http.GitlabHTTPRequestor.handleAPIError(GitlabHTTPRequestor.java:322)
    at org.gitlab.api.http.GitlabHTTPRequestor.access$300(GitlabHTTPRequestor.java:41)
    at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:217)
    ... 22 more
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://git.local.itscope.com/api/v3/projects/4/merge_requests?private_token=8e7nLHZvqLBqySS23AsZ&page=12
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
    at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:285)
    at org.gitlab.api.http.GitlabHTTPRequestor.access$200(GitlabHTTPRequestor.java:41)
    at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:213)
    ... 22 more`

**Comment by PavlikPolivka** [comment]
`"message":"500 Internal Server Error"` looks like your gitlab instace is not responding
Are you using gitlab.com or your own instace?
If your own instance what is the version you have?
Not sure how to emulate this.
