### ISSUE TITLE
neither  'Create Merge Request' nor 'list merge requests' works in webstorm and intellij idea

### ISSUE THREAD

**Issue by summerkai** [PavlikPolivka/GitLabProjects#39]
Hello,
I input something like 'http://192.168.1.10/' as the gitlab server url and input the private token from gitlab /profile/account as the gitlab api key. But when i click 'list merge requests', the below exception was pop up. Is it a bug or did i do something wrong? Please kindly provide the suggestion if there's any. Thanks in advance.
Argument for @NotNull parameter 'mergeRequestListWorker' of com/ppolivka/gitlabprojects/merge/list/GitLabMergeRequestListDialog.<init> must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'mergeRequestListWorker' of com/ppolivka/gitlabprojects/merge/list/GitLabMergeRequestListDialog.<init> must not be null
    at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListDialog.<init>(GitLabMergeRequestListDialog.java)
    at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListAction.apiValidAction(GitLabMergeRequestListAction.java:23)
    at com.ppolivka.gitlabprojects.common.GitLabApiAction.actionPerformed(GitLabApiAction.java:58)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:311)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
    at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:281)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:193)
    at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:389)
    at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:357)
    at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
    at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by PavlikPolivka** [comment]
Hi,
if you `git remote -v` on that same project in command line can you see git repository with same url in the list?
If no I cannot do anything for you, right now your project git repository must have same domain as the gitlab server your are inputing in the setting field.
If you see something with same domain can you paste example here?
I already tried 
git@192.168.1.10:Polivka/130regression.git
http://192.168.1.10/Polivka/130regression.git
and both of them are working for me.

**Comment by summerkai** [comment]
Hi,

The repository url configured in the Preference of Webstorm is definitely same with the cloned repository url which is also definitely same with the output of command 'git remote -v'. Additonally, I wrote a small python code snippet to connect with the remote gitlab server and the result is positive.  The plugin configuration as below.
<img width="1024" alt="screen shot 2016-08-29 at 10 48 24 am" src="https://cloud.githubusercontent.com/assets/13118667/18039735/260797bc-6dd8-11e6-8ef1-90426c4b03e8.png">
If you need more information for debugging, please kindly let me know. Thx!

**Comment by PavlikPolivka** [comment]
Hi, this is strange. This should be working now. There were some issues with this few versions back. What version of the plugin are you using?

**Comment by summerkai** [comment]
Hello,
The version is v1.3.6 when i installed it for the first time last week. After you replied my answer, i reinstall the plugin with the version v1.4.0 again and then i found the same problem again.

**Comment by insecure** [comment]
This is probably the same bug as #44?! See my comment there and how I "fixed" it.
I'm using 1.4.0 btw.

**Comment by stela** [comment]
I have the same exception now, but (see #44) the `<option projectId= value=> tag` was present and also checking out anew from gitlab didn't help. This feature worked in the past with an old GitLab release. Recently our GitLab installation was upgraded to (almost) the latest version, 8.14.0, and I turned on 2FA support (with a U2F device added) and created an access token, this access token apparently works for checking out the sources at least. I can still commit and push to a branch from IntelliJ.

Workaround for now: use the GitLab web interface to create or list merge requests.

**Comment by PavlikPolivka** [comment]
This should be solved by commits from #44
