### ISSUE TITLE
java.io.FileNotFoundException on attempt to import a project to GitLab

### ISSUE THREAD

**Issue by harumamburu** [PavlikPolivka/GitLabProjects#40]
I have a project I wanted to import to a GitLab private repository. I'm getting the following:

`java.io.FileNotFoundException: https://gitlab.com/u/${username}/api/v3/namespaces?private_token=${token}
java.lang.Error: java.io.FileNotFoundException: https://gitlab.com/u/${username}/api/v3/namespaces?private_token=${token}
	at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:220)
	at org.gitlab.api.http.GitlabHTTPRequestor$1.hasNext(GitlabHTTPRequestor.java:176)
	at org.gitlab.api.http.GitlabHTTPRequestor.getAll(GitlabHTTPRequestor.java:145)
	at com.ppolivka.gitlabprojects.api.ApiFacade.getNamespaces(ApiFacade.java:48)
	at com.ppolivka.gitlabprojects.share.GitLabShareDialog$2.run(GitLabShareDialog.java:110)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: https://gitlab.com/u/${username}/api/v3/namespaces?private_token=${token}
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:285)
	at org.gitlab.api.http.GitlabHTTPRequestor.access$200(GitlabHTTPRequestor.java:41)
	at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:213)
	... 17 more` 

STR:

1. VCS->Import...->Share on GitLab
2. GitLab server URL and API key are taken from IDE settings
3. Input project name, check 'private', click 'Share'. Auth type and commit message don't make any difference. 'Group' filed is empty.

I tried this with IDEA 2016.2.1 and 2016.2.2

**Comment by PavlikPolivka** [comment]
Group combo box should always contain at least Default field. It's filled with `/api/v3/namespaces` call.. 
From the stacktrace it looks like that this api call fails for you. 
Can you try this CURL call?
http://docs.gitlab.com/ce/api/namespaces.html#list-namespaces
It works for me on GitLab.com and on our custom gitlab instance.

**Comment by harumamburu** [comment]
It worked. I had a GitLab server URL of a wrong format, after fixing it the issue is gone. Thanks for your help.

**Comment by huy-lv** [comment]
So what is the right way to set up this plugin, i found some issue but got nothing, no one tell the what should be fill in "Gitlab server" when set up this plugin :(
