### ISSUE TITLE
Plugin crashes everytime when trying to connect to gitlab server

### ISSUE THREAD

**Issue by nomysz** [PavlikPolivka/GitLabProjects#44]
```
IllegalArgumentException: Argument for @NotNull parameter 'mergeRequestListWorker' of com/ppolivka/gitlabprojects/merge/list/GitLabMergeRequestListDialog. must not be null
```

**Comment by titanrat** [comment]
Same
`Argument for @NotNull parameter 'mergeRequestListWorker' of com/ppolivka/gitlabprojects/merge/list/GitLabMergeRequestListDialog.<init> must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'mergeRequestListWorker' of com/ppolivka/gitlabprojects/merge/list/GitLabMergeRequestListDialog.<init> must not be null
	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListDialog.<init>(GitLabMergeRequestListDialog.java)
	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListAction.apiValidAction(GitLabMergeRequestListAction.java:23)
	at com.ppolivka.gitlabprojects.common.GitLabApiAction.actionPerformed(GitLabApiAction.java:58)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.a(ActionMenuItem.java:304)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:905)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:284)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.a(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:123)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:109)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:793)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:625)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by rlalak** [comment]
I have this error too.

**Comment by titanrat** [comment]
Cloning project from gitLAB repository type (not git) solves this problem

**Comment by rlalak** [comment]
Still the same error.
I clone repository using menu VCS -> Checkout from Version Control -> GitLab

**Comment by insecure** [comment]
I had this problem, too. So i cloned to new directory via VCS->Checkout from Version Control->GitLab created a new project and compared the project files in .idea. The thing that was missing in the old tree was a setting in workspace.xml:
```xml
  <component name="GitlabProjectsProjectSettings">
    <option name="projectId" value="408" />
  </component>
```
Adding this to workspace.xml in the old tree fixed the issue, no idea though how to fix this via GUI.

**Comment by PavlikPolivka** [comment]
Hi sorry for very late response I had very busy last few months. 
The xml setting in workspace.xml does not have be present for this to work. When there are GitLab API actions that require project ID (list and creation of merge requests) it will check if the xml snippet is present (from previous run) and if not it will resolve the project id from api and saves it to workspace.xml.

Resolving works like this:
- Via API call it downloads all projects that user has access to. 
- it iterates over them until it finds one project with same name or remote url
```
          for (GitlabProject gitlabProject : projects) {
            if (gitlabProject.getName().equals(remoteProjectName) || gitlabProject.getSshUrl().equals(remoteUrl) || gitlabProject.getHttpUrl().equals(remoteUrl)) {
              projectId = gitlabProject.getId();
              projectState.setProjectId(projectId);
              break;
            }
          }
```
When project is not found right now it returns null and the whole action goes to error. It should display user friendly error dialog (not happening right now).

My guess here is that either gitlab api is not returning all the possible projects (can be tested).

Or there is something strange with the checkout url.

**Comment by stela** [comment]
Also had the same issue. In my case it was fixed by removing my old gitlab personal access token (possibly created with a pretty old GitLab release, now upgraded), creating a new one and entering that one into the text field you get when listing merge requests.

In addition, in the past I wasn't able to use VCS - Checkout from Version Control - GitLab, which is probably not dependent on the currently open project. It just hung forever while retrieving the list of projects, could only see an old probably cached version of the projects list. It doesn't let you enter a new personal access token there btw which could be convenient. Now it works again.

**Comment by PavlikPolivka** [comment]
After some investigation and tip from #47 I determined that url matching for project is way to strict. I will write less strict matching, this should solve this issue.
