### ISSUE TITLE
Java exception while sharing project

### ISSUE THREAD

**Issue by cebas** [PavlikPolivka/GitLabProjects#59]
Hi, I'm having a problem with your plugin. I have latest PHPstorm installed (171.3780.104) and the plugin 1.4.3.

steps to reproduce:
create idea project with files in it
haven't created local git repo yet
share on gitlab (gitlab.com + my api key)
group list is empty (refresh doesn't work either) (I used to see my groups here and also I was able to share projects this way)
close dialog
IDE fatal error: java.net.MalformedURLException: no protocol: gitlab.com/api/v3/namespaces

detail:
java.net.MalformedURLException: no protocol: gitlab.com/api/v3/namespaces
java.lang.Error: java.net.MalformedURLException: no protocol: gitlab.com/api/v3/namespaces
	at org.gitlab.api.http.GitlabHTTPRequestor$1.<init>(GitlabHTTPRequestor.java:187)
	at org.gitlab.api.http.GitlabHTTPRequestor.asIterator(GitlabHTTPRequestor.java:179)
	at org.gitlab.api.http.GitlabHTTPRequestor.getAll(GitlabHTTPRequestor.java:159)
	at com.ppolivka.gitlabprojects.api.ApiFacade.getNamespaces(ApiFacade.java:50)
	at com.ppolivka.gitlabprojects.share.GitLabShareDialog$2.run(GitLabShareDialog.java:110)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.MalformedURLException: no protocol: gitlab.com/api/v3/namespaces
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.gitlab.api.GitlabAPI.getAPIUrl(GitlabAPI.java:99)
	at org.gitlab.api.http.GitlabHTTPRequestor$1.<init>(GitlabHTTPRequestor.java:185)
	... 17 more

thanks

**Comment by PavlikPolivka** [comment]
Hi sorry for late response.

The url mus be filled with the protocol so https://gitlab.com

There is a lots of confusion for the setting screen. I will do some changes to make it more clear.

**Comment by cebas** [comment]
Hi, 
it's working now. Thanks!

I suggest at least add a default url or a help text in the form. Also a proper error message instead of an exception would be nicer ;-)
