### ISSUE TITLE
Error on List Merge Request

### ISSUE THREAD

**Issue by jonathanbenedet** [PavlikPolivka/GitLabProjects#65]
Plugin Error: GitLab Projects threw an uncaught IllegalArgumentException. Disable Plugin

15:00	IllegalArgumentException: Argument for @NotNull parameter 'mergeRequestListWorker' of com/ppolivka/gitlabprojects/merge/list/GitLabMergeRequestListDialog.<init> must not be null

15:00	Cannot Create Merge Request: Cannot find this project in GitLab Remote

**Comment by PavlikPolivka** [comment]
What OS, IDE?? More details please. This is completely out of context and I cannot help you like this.
Thanks.

**Comment by michalhudecek** [comment]
I get the same error when I click List Merge request in the menu. 
Windows 10
PHP Storm 2017.2

Fatal error details:

`Argument for @NotNull parameter 'mergeRequestListWorker' of com/ppolivka/gitlabprojects/merge/list/GitLabMergeRequestListDialog.<init> must not be null`

`Argument for @NotNull parameter 'mergeRequestListWorker' of com/ppolivka/gitlabprojects/merge/list/GitLabMergeRequestListDialog.<init> must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'mergeRequestListWorker' of com/ppolivka/gitlabprojects/merge/list/GitLabMergeRequestListDialog.<init> must not be null
	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListDialog.$$$reportNull$$$0(GitLabMergeRequestListDialog.java)
	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListDialog.<init>(GitLabMergeRequestListDialog.java)
	at com.ppolivka.gitlabprojects.merge.list.GitLabMergeRequestListAction.apiValidAction(GitLabMergeRequestListAction.java:23)
	at com.ppolivka.gitlabprojects.common.GitLabApiAction.actionPerformed(GitLabApiAction.java:58)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.a(ActionMenuItem.java:310)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:911)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:300)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.a(ActionMenuItem.java:117)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:117)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by PavlikPolivka** [comment]
This seems to be the same reason as in #69, it cannot find what is your gitlab project from the remote urls. 
Need more info (described in #69) to debug this.

**Comment by michalhudecek** [comment]
I fixed this by changing lowercase/uppercase in repo address in git config. See my comments in #69

**Comment by PavlikPolivka** [comment]
Should be fixed by #69.
